# Generated by Django 4.0.4 on 2023-05-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BIO', 'Bio et écologie'), ('FRUITS_ET_LEGUMES', 'Fruits et légumes'), ('VIANDE_ET_POISSON', 'Viande et poisson')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
