# Generated by Django 4.0.4 on 2023-05-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BIO', 'Bio et écologie'), ('FRUITS_ET_LEGUMES', 'Fruits et légumes'), ('VIANDE_ET_POISSON', 'Viande et poisson'), ('PAIN_ET_PATISSERIE', 'Pain et pâtisseries'), ('FRAIS', 'Produits frais'), ('SURGELE', 'Surgelés'), ('BOISSONS', 'Boissons'), ('EPICERIE_SALEE', 'Epicerie salée'), ('EPICERIE_SUCREE', 'Epicerie sucrée'), ('PRODUITS_DU_MONDE', 'Produits du monde')], max_length=32, null=True)),
            ],
        ),
    ]
