# Generated by Django 4.0.4 on 2023-05-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_category_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='start_date',
            field=models.DateField(),
        ),
    ]
