# Generated by Django 4.0.4 on 2023-05-11 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_remove_sales_product_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='percentage',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
