# Generated by Django 4.0.4 on 2023-05-11 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_sales_name_alter_sales_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales',
        ),
        migrations.AddField(
            model_name='sales',
            name='sales',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sales.product'),
        ),
    ]
