# Generated by Django 4.0.4 on 2023-05-11 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_rename_sales_sales_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
